name: ZAP-Scanner

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'The URL to scan'
        required: true
      scan_type:
        description: 'Type of scan: baseline or full'
        required: true
        default: 'baseline'

permissions: write-all

jobs:

  zap_scan:
    runs-on: ubuntu-latest
    name: Run DAST scan on the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: ZAP Baseline Scan
        if: ${{ inputs.scan_type == 'basline' }}
        uses: zaproxy/action-baseline@v0.14.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: ${{ inputs.target }}
          cmd_options: '-a'

      - name: ZAP Full Scan
        if: ${{ inputs.scan_type == 'full' }}
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: ${{ inputs.target }}
          cmd_options: '-a'
