name: ZAP-Scanner

on:
  push:
  workflow_dispatch:
    inputs:
      target:
        description: 'The URL to scan'
        required: true

permissions: write-all

jobs:

  zap_scan:
    runs-on: ubuntu-latest
    name: Run DAST scan on the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: ${{ inputs.target }}
          cmd_options: '-a'
